parameters:
    upload_listener.class: Bacon\Bundle\MediaLibraryBundle\EventListener\UploadListener
    upload_entity.class: Bacon\Bundle\MediaLibraryBundle\Entity\MediaLibrary
    form_type_extension.class: Bacon\Bundle\MediaLibraryBundle\Form\Type\MediaLibraryType
    form_data_transformer: Bacon\Bundle\MediaLibraryBundle\Form\DataTransformer\MediaLibraryFormTransformer

services:
    bacon.media_library.upload_listener:
        class: "%upload_listener.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
        calls:
             - [setClassEntity, ['%upload_entity.class%']]
             - [setLiipCacheManager, ['@liip_imagine.cache.manager']]

    bacon.media_library.form_type.media_library_type_extension:
        class: "%form_type_extension.class%"
        tags:
            - { name: form.type }
        calls:
            - [setModelTransformer, ["@bacon.media_library.form_data_transformer.instance"]]

    bacon.media_library.form_data_transformer.instance:
        class: "%form_data_transformer%"
        arguments: ["@doctrine.orm.entity_manager"]
